# Generated by Django 2.1.7 on 2019-02-12 13:01

from django.db import migrations, models
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('td_prn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathreport',
            name='death_date',
            field=models.DateField(validators=[edc_base.model_validators.date.date_not_future], verbose_name='Date of Death:'),
        ),
        migrations.AlterField(
            model_name='historicaldeathreport',
            name='death_date',
            field=models.DateField(validators=[edc_base.model_validators.date.date_not_future], verbose_name='Date of Death:'),
        ),
    ]
