# Generated by Django 2.1.5 on 2019-02-14 07:20

from django.db import migrations, models
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('td_prn', '0002_auto_20190212_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaternaloffstudy',
            name='last_study_fu_date',
            field=models.DateField(blank=True, null=True, validators=[edc_base.model_validators.date.date_not_future], verbose_name='Date of last research follow up (if different):'),
        ),
        migrations.AddField(
            model_name='maternaloffstudy',
            name='last_study_fu_date',
            field=models.DateField(blank=True, null=True, validators=[edc_base.model_validators.date.date_not_future], verbose_name='Date of last research follow up (if different):'),
        ),
    ]
