# Generated by Django 2.1.5 on 2019-02-20 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import edc_base.model_validators.date
import edc_base.sites.managers
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('td_prn', '0004_auto_20190215_1037'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='maternaloffstudy',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalmaternaloffstudy',
            name='offstudy_datetime',
        ),
        migrations.RemoveField(
            model_name='historicalmaternaloffstudy',
            name='offstudy_reason',
        ),
        migrations.RemoveField(
            model_name='historicalmaternaloffstudy',
            name='offstudy_reason_other',
        ),
        migrations.RemoveField(
            model_name='historicalmaternaloffstudy',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='historicalmaternaloffstudy',
            name='visit_schedule_name',
        ),
        migrations.RemoveField(
            model_name='maternaloffstudy',
            name='offstudy_datetime',
        ),
        migrations.RemoveField(
            model_name='maternaloffstudy',
            name='offstudy_reason',
        ),
        migrations.RemoveField(
            model_name='maternaloffstudy',
            name='offstudy_reason_other',
        ),
        migrations.RemoveField(
            model_name='maternaloffstudy',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='maternaloffstudy',
            name='visit_schedule_name',
        ),
        migrations.AddField(
            model_name='historicalmaternaloffstudy',
            name='offschedule_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time subject taken off schedule'),
        ),
        migrations.AddField(
            model_name='historicalmaternaloffstudy',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='maternaloffstudy',
            name='offschedule_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time subject taken off schedule'),
        ),
        migrations.AddField(
            model_name='maternaloffstudy',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
    ]
