# Generated by Django 2.1.5 on 2019-02-20 07:58

from django.db import migrations, models
import edc_base.model_fields.custom_fields
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('td_prn', '0005_auto_20190220_0859'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='maternaloffstudy',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='historicalmaternaloffstudy',
            name='offschedule_datetime',
        ),
        migrations.RemoveField(
            model_name='historicalmaternaloffstudy',
            name='site',
        ),
        migrations.RemoveField(
            model_name='maternaloffstudy',
            name='offschedule_datetime',
        ),
        migrations.RemoveField(
            model_name='maternaloffstudy',
            name='site',
        ),
        migrations.AddField(
            model_name='historicalmaternaloffstudy',
            name='offstudy_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Off-study date and time'),
        ),
        migrations.AddField(
            model_name='historicalmaternaloffstudy',
            name='offstudy_reason',
            field=models.CharField(choices=[('lost', 'Lost to follow-up'), ('completed protocol', 'Completed protocol'), ('consent_withdrawal', 'Completed protocol'), ('dead', 'Deceased')], default=1, max_length=125, verbose_name='Please code the primary reason participant taken off-study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmaternaloffstudy',
            name='offstudy_reason_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AddField(
            model_name='historicalmaternaloffstudy',
            name='schedule_name',
            field=models.CharField(default=1, editable=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmaternaloffstudy',
            name='visit_schedule_name',
            field=models.CharField(default=1, editable=False, help_text='the name of the visit schedule used to find the "schedule"', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maternaloffstudy',
            name='offstudy_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Off-study date and time'),
        ),
        migrations.AddField(
            model_name='maternaloffstudy',
            name='offstudy_reason',
            field=models.CharField(choices=[('lost', 'Lost to follow-up'), ('completed protocol', 'Completed protocol'), ('consent_withdrawal', 'Completed protocol'), ('dead', 'Deceased')], default=1, max_length=125, verbose_name='Please code the primary reason participant taken off-study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maternaloffstudy',
            name='offstudy_reason_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AddField(
            model_name='maternaloffstudy',
            name='schedule_name',
            field=models.CharField(default=1, editable=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maternaloffstudy',
            name='visit_schedule_name',
            field=models.CharField(default=1, editable=False, help_text='the name of the visit schedule used to find the "schedule"', max_length=25),
            preserve_default=False,
        ),
    ]
